
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  jpa:
    database: H2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/db/rosieedb/rosiee;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;
    username: sa
    password: 
  flyway:
    user: sa
    password:
    schemas: PUBLIC